url: https://sanguinefish.github.io
baseurl: /digifaire_grants/

# Site settings
title: Digifaire 
email: support@digifaire.com
description: "Developmental & Grant Writing Services"


- name: Raju Basumatary
  pic: 2
  position: Team Leader
  social:
    - title: #
      url: #
    - title: #
      url: #
    - title: #
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: #
    url: #
  - title: #
    url: #
  - title: #
    url: #
  - title: #
    url: #
  - title: github
    url: http://github.com/digifaire

# Postal address (add as many lines as necessary)
address:
  - line: #
  - line: #

# Build settings
markdown: kramdown
permalink: pretty
